print("Welcome in a Trik game of Mind by Math")
print("Game rule is to simple, You just thought a number between 1 to 9 and I will try to guess it ;)")
print(input("If you have guessed then say me yes: "))
print(input("okey, now multiply by 2 and if you have done say me yes: "))
print(input("now again 1 more time multiply by 2 and if you have done say me yes: "))
a = int(input("now multiply by 5 and say me the result: "))
print("hmm, interesting...")
print("Are you think about", a/20, "?")
print(input("If I am right say me yes: "))