print("Welcome in a Trik game of Mind by Math")
print("Game rule is simple, You just have to think a number between 1 to 9 and I will try to guess it ;)")
print(input("If you have guessed a number then press enter: "))
print(input("Okey, now multiply it by 2 and then press enter: "))
print(input("Now again one more time multiply it by 2 and then press enter: "))
a = int(input("Now multiply it by 5 and write the result: "))
print("Hmm, interesting...")
print("Are you think about", a/20, "?")
print(input("Thank You for playing"))